// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Download
---
*/
package cmds

import (
	"context"

	"github.com/365admin/sharepoint-download/execution"
	"github.com/365admin/sharepoint-download/utils"
)

func SandboxDownloadPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "sharepoint-download", "90-sandbox", "10-download.ps1", "", "-siteurl", args[0], "-folderref", args[1], "-filename", args[2], "-copyto", args[3])
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
